name: hello-world
on: push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: read txt file
        run: echo "${cat hello_world.txt}"
